### ISSUE TITLE
in_array error on /modules.php

### ISSUE THREAD

**Issue by AlcaDesign** [MJRLegends/MJRBot-Server#1]
I got this PHP error on this page: `https://mjrbot.mjrlegends.com/modules.php`

>Warning: `in_array()` expects parameter 2 to be `array`, `null` given in `/var/www/mjrbot/modules.php` on *line 283*

![image](https://user-images.githubusercontent.com/7132646/55930534-5f8a8f80-5be7-11e9-8dd3-e3b792e5bde0.png)

**Comment by MJRLegends** [comment]
Thank for the report. Yea, its on the list to fix. Just haven't got around to it yet. Let me know if you find any more.

**Comment by MJRLegends** [comment]
Side note: It will fix it self up once the bot has joined your channel. Its just a harmless issue so you should be fine to carry on using it.

**Comment by MJRLegends** [comment]
Issue has been fixed
