### ISSUE TITLE
Adding the bad words

### ISSUE THREAD

**Issue by ikeepitlow** [MJRLegends/MJRBot-Server#2]
Hello. When I was adding the bad words, I have encountered this error
![image](https://user-images.githubusercontent.com/58445845/69994478-4061b900-154e-11ea-9199-fae5a1fd207a.png)

I was trying to add my national bad words. [PL]

**Comment by MJRLegends** [comment]
Thanks issue has been resolved, btw im currently updating the bot so it will be back up very soon :D
